### ISSUE TITLE
Error provisoning desktop

### ISSUE THREAD

**Issue by fsacer** [cliffe/SecGen#100]
I had error when provisioning desktop vm  `Evaluation Error: Error while evaluating a Function Call, Could not find class ::unix_update::unix`  in security audit scenario.

**Comment by cliffe** [comment]
Thanks. Which scenario?

**Comment by cliffe** [comment]
Tested working on my system.

Could be a symptom of not having all of SecGen's dependencies installed correctly. Did you run bundle install?

**Comment by fsacer** [comment]
I had all dependencies installed and did bundle install. I tested it a again and it went through without error.

**Comment by fsacer** [comment]
It might be dependant on specific so here is XML.
[scenario.xml.zip](https://github.com/cliffe/SecGen/files/1236918/scenario.xml.zip)

**Comment by thomashaw** [comment]
Hi @fsacer,

I ran SecGen with your scenario file and had an error when provisioning the samba_symlink_traversal module on the intranet_server. I've pushed a fix up for this, thanks for sharing the scenario.xml.

The desktop machine provisioned fine for me so I'm going to close the issue. 

Cheers!
