### ISSUE TITLE
WARN: Unresolved specs during Gem::Specification.reset:

### ISSUE THREAD

**Issue by Ysagi** [cliffe/SecGen#105]
Hello.

I have installed SecGen but when running:
$ ruby secgen.rb run

I get the error:
Loading vagrant (up) in /home/mattias/SecGen/projects/SecGen20170829_1036
WARN: Unresolved specs during Gem::Specification.reset:
      nokogiri (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Bringing machine 'storage_server' up with 'virtualbox' provider...
/usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:126:in `join': No live threads left. Deadlock? (fatal)
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:126:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:65:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:65:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:258:in `block (2 levels) in batch'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:253:in `tap'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:253:in `block in batch'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:252:in `synchronize'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:252:in `batch'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/commands/up/command.rb:88:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:274:in `cli'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/bin/vagrant:122:in `<top (required)>'
	from /usr/bin/vagrant:22:in `load'
	from /usr/bin/vagrant:22:in `<main>'
VMs created.

No VMs are created :-(

How to resolve this?

best regards Mattias

**Comment by Chan9390** [comment]
Hey @Ysagi I feel that you did not run the bundler. Did you try running the command `bundle install` ?
Also provide the output of `gem list`

**Comment by Ysagi** [comment]
Hello again. 

I did bundle install,  but was running as root when I did it. Can that be a problem?

$ bundle install
Using rake 11.1.2
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using CFPropertyList 2.2.8
Using json_pure 1.8.3
Using thor 0.19.1
Using multipart-post 2.0.0
Using minitar 0.5.4
Using semantic_puppet 0.1.3
Using rsync 1.0.9
Using i18n 0.7.0
Using forgery 0.6.0
Using redcarpet 3.4.0
Using chunky_png 1.3.8
Using mini_exiftool 2.8.0
Using rmagick 2.16.0
Using sshkey 1.9.0
Using minitest 5.9.0
Using json 1.8.3
Using yard 0.8.7.6
Using bundler 1.15.1
Using nokogiri 1.6.8
Using facter 2.4.6
Using hiera 3.2.0
Using librarianp 0.6.3
Using faraday 0.9.2
Using faker 1.6.6
Using rqrcode 0.10.1
Using mini_exiftool_vendored 9.2.7.v1
Using rdoc 4.2.2
Using spidr 0.6.0
Using puppet 4.5.1
Using faraday_middleware 0.10.0
Using wordlist 0.1.1
Using puppet_forge 2.2.1
Using librarian-puppet 2.2.3
Bundle complete! 15 Gemfile dependencies, 36 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
The latest bundler is 1.15.4, but you are currently running 1.15.1.
To update, run `gem install bundler`

$ gem list

*** LOCAL GEMS ***

addressable (2.5.1)
ansi (1.5.0)
atomic (1.1.16)
bcrypt_pbkdf (1.0.0)
bigdecimal (1.2.8)
buftok (0.2.0)
bundler (1.15.4, 1.15.1)
celluloid (0.16.0)
celluloid-io (0.16.2)
CFPropertyList (2.2.8)
childprocess (0.5.9)
chunky_png (1.3.8)
daemons (1.1.9)
data_objects (0.10.16)
did_you_mean (1.0.0)
diff-lcs (1.3)
dm-core (1.2.1)
dm-do-adapter (1.2.0)
dm-migrations (1.2.0)
dm-serializer (1.2.2)
dm-sqlite-adapter (1.2.0)
do_mysql (0.10.16)
do_postgres (0.10.16)
do_sqlite3 (0.10.16)
docile (1.1.5)
domain_name (0.5.20160216)
em-websocket (0.5.1)
equalizer (0.0.11)
erubis (2.7.0)
ethon (0.9.0)
eventmachine (1.0.7)
execjs (2.6.0)
facter (2.4.6)
faker (1.6.6)
faraday (0.9.2)
faraday_middleware (0.10.0)
ffi (1.9.10)
forgery (0.6.0)
geoip (1.4.0)
hiera (3.2.0)
hitimes (1.2.1)
http (2.2.2)
http-cookie (1.0.2)
http-form_data (1.0.1)
http_parser.rb (0.6.0)
httpclient (2.8.3)
i18n (0.7.0)
io-console (0.4.5)
json (2.1.0, 1.8.3)
json_pure (1.8.3)
librarian-puppet (2.2.3)
librarianp (0.6.3)
librex (0.0.68)
libv8 (3.16.14.13)
listen (3.0.3)
log4r (1.1.10)
memoizable (0.4.2)
mime (0.4.3)
mime-types (3.1)
mime-types-data (3.2015.1120)
mini_exiftool (2.8.0)
mini_exiftool_vendored (9.2.7.v1)
mini_portile2 (2.2.0, 2.1.0)
minitar (0.5.4)
minitest (5.10.3, 5.9.0)
mojo_magick (0.5.6)
molinillo (0.5.0)
msfrpc-client (1.0.1)
msgpack (1.0.0)
multi_json (1.12.1)
multipart-post (2.0.0, 1.2.0)
naught (1.1.0)
net-http-digest_auth (1.4)
net-http-persistent (2.9.4)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (4.1.0)
net-telnet (0.1.1)
netrc (0.11.0)
nio4r (1.2.1)
nokogiri (1.8.0, 1.6.8)
oj (2.17.4)
parseconfig (1.0.2)
pkg-config (1.2.7, 1.1.7)
power_assert (0.2.7)
psych (2.1.0)
public_suffix (2.0.5)
puppet (4.5.1)
puppet_forge (2.2.1)
qr4r (0.4.0)
rack (1.6.4)
rack-protection (1.5.3)
rake (12.0.0, 11.1.2)
rb-inotify (0.9.7)
rbnacl (5.0.0)
rchardet (1.6.1)
rdoc (4.2.2, 4.2.1)
redcarpet (3.4.0)
ref (2.0.0)
rest-client (2.0.2)
rmagick (2.16.0)
rqrcode (0.10.1, 0.4.2)
rspec-expectations (3.5.0)
rspec-support (3.5.0)
rsync (1.0.9)
ruby-progressbar (1.6.0)
rubydns (1.0.3)
rubyzip (1.2.1)
semantic_puppet (0.1.3)
simple_oauth (0.3.1)
simplecov (0.14.1)
simplecov-html (0.10.0)
sinatra (1.4.7)
snmp (1.2.0)
spider (0.32)
spidr (0.6.0)
sqlite3 (1.3.13)
sshkey (1.9.0)
term-ansicolor (1.3.0)
terminal-table (1.6.0)
test-unit (3.2.5)
therubyracer (0.12.2)
thin (1.6.3)
thor (0.19.4, 0.19.1)
thread_safe (0.3.5)
tilt (2.0.1)
timers (4.1.1)
tins (1.1.0)
twitter (6.1.0)
typhoeus (1.1.2)
uglifier (2.7.2)
unf (0.1.4)
unf_ext (0.0.7.2)
vagrant (1.9.1)
wordlist (0.1.1)
yajl-ruby (1.2.0)
yard (0.8.7.6)
zipruby (0.3.6)

Best regards Mattias

**Comment by Chan9390** [comment]
Not sure if installing gem as root is a problem. *But try running as a normal user*. I have seen scenarios where installing vagrant images with sudo privileges installs the VM, but they are not visible to normal user.

**Comment by cliffe** [comment]
Hi. This seems to be related to [https://github.com/mitchellh/vagrant/issues/8125](https://github.com/mitchellh/vagrant/issues/8125)
Please try reinstalling vagrant (potentially a different version?)

**Comment by Ysagi** [comment]
Hello cliffe.

You solved my problem, thank you very much. 

I tried to reinstall vagrant v1.9.1 but the same issue remained, but downloading the latest version from HasiCorp vagrant v1.9.8 solved this.

Thanks Mattias

**Comment by Ysagi** [comment]
This issue can be closed.

/Mattias

**Comment by cliffe** [comment]
Glad this helped, @Ysagi. Thanks also to @Chan9390 for taking the time to weigh in.
