### ISSUE TITLE
librarian (LoadError)

### ISSUE THREAD

**Issue by k32237h** [cliffe/SecGen#107]
Hey I am running into this issue have tried a couple of things but no luck. I made sure I followed all instructions as well. I am running Linux Mint 18.2 KDE.

when I run ruby secgen.rb run I get this response

/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- librarian (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/k32237h/SecGen/lib/output/project_files_creator.rb:6:in `<top (required)>'
        from secgen.rb:9:in `require_relative'
        from secgen.rb:9:in `<main>'

Any help on this would be much appreciated.

Thank you.

**Comment by cliffe** [comment]
Try:
sudo gem install librarian-puppet librarianp

**Comment by k32237h** [comment]
Thanks that started the create process then this showed up.

There are errors in the configuration of this machine. Please fix
the following errors and try again:

puppet provisioner:
* The manifests path specified for Puppet does not exist: /home/k32237h/SecGen/projects/SecGen20170928_0701/puppet/storage_server/modules/unix_update
* The manifests path specified for Puppet does not exist: /home/k32237h/SecGen/projects/SecGen20170928_0701/puppet/storage_server/modules/apache
* The manifests path specified for Puppet does not exist: /home/k32237h/SecGen/projects/SecGen20170928_0701/puppet/storage_server/modules/moinmoin_195
* The manifests path specified for Puppet does not exist: /home/k32237h/SecGen/projects/SecGen20170928_0701/puppet/storage_server/modules/nmap
* The manifests path specified for Puppet does not exist: /home/k32237h/SecGen/projects/SecGen20170928_0701/puppet/storage_server/modules/setuid_nmap
* The manifests path specified for Puppet does not exist: /home/k32237h/SecGen/projects/SecGen20170928_0701/puppet/storage_server/modules/unrealirc


Error creating VMs, Exiting SecGen.


It creates the path up to the last folder but no files are in each of the last folders.

**Comment by cliffe** [comment]
Did you run "bundle install", when installing SecGen? Maybe try again.

**Comment by k32237h** [comment]
Yeah I did, tried it again and no luck. I even tried deleting the folder and starting fresh and got a similar response

There are errors in the configuration of this machine. Please fix
the following errors and try again:

puppet provisioner:
* The manifests path specified for Puppet does not exist: /home/k32237h/SecGen/projects/SecGen20170928_2352/puppet/storage_server/modules/unix_update
* The manifests path specified for Puppet does not exist: /home/k32237h/SecGen/projects/SecGen20170928_2352/puppet/storage_server/modules/apache
* The manifests path specified for Puppet does not exist: /home/k32237h/SecGen/projects/SecGen20170928_2352/puppet/storage_server/modules/moinmoin_195
* The manifests path specified for Puppet does not exist: /home/k32237h/SecGen/projects/SecGen20170928_2352/puppet/storage_server/modules/nmap
* The manifests path specified for Puppet does not exist: /home/k32237h/SecGen/projects/SecGen20170928_2352/puppet/storage_server/modules/setuid_nmap
* The manifests path specified for Puppet does not exist: /home/k32237h/SecGen/projects/SecGen20170928_2352/puppet/storage_server/modules/samba


Error creating VMs, Exiting SecGen.

**Comment by cliffe** [comment]
Looks like a problem with librarian-puppet. Could be a problem specific
to Mint? Perhaps try to install the Librarian Puppet gem from another
source.

**Comment by k32237h** [comment]
I reinstalled librarian-puppet and it worked!

Thanks again for all of your help!

**Comment by cliffe** [comment]
Great. Glad it's sorted. Have fun with SecGen!
