### ISSUE TITLE
Vagrant Host URL Download Error

### ISSUE THREAD

**Issue by kknisely** [cliffe/SecGen#110]
I receive errors when trying to start up a VM with the default scenario. Found that the host url for downloading vagrant boxes has changed. What is the best way to update the metadata under Modules to correct this issue?

New Metadata URL: https://vagrantcloud.com

**Comment by cliffe** [comment]
Hi @kknisely. Thanks for letting us know. We are currently working on merging a bunch of work over the last 6 months or so into master. The upcoming merge happens to also include a fix for this issue, so in the meantime you could checkout the "merge" branch. We will close this issue once the changes are merged into master.

**Comment by cliffe** [comment]
@thomashaw has just merged into master amongst other things a fix for this issue. Thanks again.
