### ISSUE TITLE
How to access the created VMs?

### ISSUE THREAD

**Issue by ZamAli** [cliffe/SecGen#112]
Once the installation is done, it shows "VMs created ". My question is where are those VMs created? How can i access the VMs individually? i suppose with one specific vulnerability it creates only one VM, to create another VM with a different vulnerability, i have to create another linux machine in the virtualbox and then install the SecGen again and then create a VM. is that so? Or i can create as many VMs with different vulnerabilities in just one linux machine with SecGen installed in it?

**Comment by cliffe** [comment]
If you start Virtualbox you will see all the VMs. You should restart them 
then depending on the scenario you typically want to connect to them via 
the network to attack the VM. Some of the scenarios include the attacking 
VM and some include desktop systems. You can create as many VMs as you like!

On 4 April 2018 8:31:33 am Zubair Ali <notifications@github.com> wrote:
Once the installation is done, it shows "VMs created ". My question is 
where are those VMs created? How can i access the VMs individually? i 
suppose with one specific vulnerability it creates only one VM, to create 
another VM with a different vulnerability, i have to create another linux 
machine in the virtualbox and then install the SecGen again and then create 
a VM. is that so? Or i can create as many VMs with different 
vulnerabilities in just one linux machine with SecGen installed in it?
