### ISSUE TITLE
Undefined method `[]' for nil:NilClass when provisioning proftpd

### ISSUE THREAD

**Issue by MelintonN** [cliffe/SecGen#118]
I wrote a scenario that included the proftpd service and everything runs good until it tries to provision the proftpd module. I've reviewed some of the configuration and templates regarding proftpd but hadn't find anything. I would appreciate any help. 

Error: Evaluation Error: Error while evaluating a Function Call, Failed to parse template proftpd/proftpd.erb:
==> escuela_final_4:   Filepath: /tmp/vagrant-puppet/modules-c6c9757ce2e4393b325bd712cf459896/proftpd/templates/proftpd.erb
==> escuela_final_4:   Line: 1
==> escuela_final_4:   Detail: undefined method ´[]' for nil:NilClass
==> escuela_final_4:  at /tmp/vagrant-puppet/modules-c6c9757ce2e4393b325bd712cf459896/proftpd/manifests/configure.pp:9:17 on node localhost.localdomain
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by thomashaw** [comment]
Hi @MelintonN 

Thank you for raising this issue. It should be fixed now, just pull down the latest commit.

Cheers!
Tom
