### ISSUE TITLE
Failed to read scenario configuration file

### ISSUE THREAD

**Issue by LarryCheech** [cliffe/SecGen#119]
Hay,

I have installed SecGen as directed without any issues but when I run the following command;

ruby secgen.rb --scenario scenarios/security_audit/team_project_scenario.xml run

I get an error stating 'Failed to read scenario configuration file'

Any advice? Running on ubuntu server 18

**Comment by cliffe** [comment]
The file was renamed. Please try
ruby secgen.rb --scenario scenarios/security_audit/team_project.xml run

**Comment by LarryCheech** [comment]
Wow, really embarrassing, thank you.

**Comment by cliffe** [comment]
No worries ;)
