### ISSUE TITLE
undefined method 'first' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by putako** [cliffe/SecGen#121]
I have successfully used (some of) the built-in scenarios to create VMs.
I have my own Windows basebox that I have created a secgen_metadata.xml for.
I created a scenario for it.  When I try "ruby secgen.rb -s [scenario.xml] p" i get the error:
`Checking to see if local basebox [windows basebox] exists
Traceback (most recent call last):
	6: from secgen.rb:464:in '<main>'
	5: from secgen.rb:116:in 'build_config'
	4: from /[path]/bin/secgen/lib/output/project_files_creator.rb:60:in 'write_files'
	3: from /[path]/bin/secgen/lib/output/project_files_creator.rb:60:in 'each'
	2: from /[path]/bin/secgen/lib/output/project_files_creator.rb:73:in 'block in write_files'
	1: from /[path]/bin/secgen/lib/output/project_files_creator.rb:73:in 'each'
/[path]/bin/secgen/lib/output/project_files_creator.rb:80:in 'block (2 levels) in write_files': undefined method 'first' for nil:NilClass (NoMethodError)
`

**Comment by putako** [comment]
changed url tag, working now

**Comment by cliffe** [comment]
Glad to hear you got this sorted. We could benefit from a lot more Windows content. What are you working on?

**Comment by putako** [comment]
Me and some buddies are putting together a little cyber lab for fun. Your
SecGen has really helped us already.
