### ISSUE TITLE
please help me to solve this problem..

### ISSUE THREAD

**Issue by acekingred** [cliffe/SecGen#123]
exec '' --preserve-environment -c 'LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets /data/data/com.termux/files/usr/bin/bash'
/data/data/com.termux/files/usr/bin/tsu: line 139: exec: : not found
$

**Comment by cliffe** [comment]
Doesn't look related to SecGen?
