### ISSUE TITLE
scenarios/ctf/basic_narrative.xml results in broken DB

### ISSUE THREAD

**Issue by Da5hes** [cliffe/SecGen#124]
when running the scenario the outputted vm is working ok, except for the database of the onlinestore module which is not populated with the right values, some tables are empty(for example users table), others are truncated such as: only half of the flag is present in token table

**Comment by thomashaw** [comment]
Hi @Da5hes,

Thanks for highlighting this. Apologies for the long delay, I will be taking a look at this tomorrow.

Cheers,
Tom

**Comment by profzeller** [comment]
Tom,

I wrote several scenarios around this code recently. Found several things like its and did some workarounds as I was under a deadline. This will work if you force it to be a hex flag. It does not like the concat flag generator.

**Comment by thomashaw** [comment]
Oh thanks a lot @profzeller , that saves me some time! Unfortunately I hadn't managed to get around to looking at this issue due to other priorities.  It most likely be getting fixed next week along with a merge of all of the other changes we've made over the course of this semester.

**Comment by profzeller** [comment]
@thomashaw There is also issues with the parameterised_website in this scenario. None of the message content shows up. I believe it was an issue with html_snippet but I don't remember. I will look through the fixes I did in my scenario based off that one.

**Comment by thomashaw** [comment]
Should be fixed in the current master branch.

I'm also going to merge an update to the scenario file later today that includes a Kali VM which automatically opens Firefox/iceweasel with the target machines IP:80 as a home page.
