### ISSUE TITLE
NFS share leak

### ISSUE THREAD

**Issue by kuhioday** [cliffe/SecGen#128]
Maybe I'm missing something, but when I mount the export folder given through NFS, I can't read any of the files. Am I doing it wrong, or is there something wrong here?

**Comment by thomashaw** [comment]
Hey @kuhioday, 

Thanks for letting us know about this. It should be fixed in 201fd77 if you update master.

Cheers,
Tom

**Comment by kuhioday** [comment]
Thanks for getting to this so quick!
