### ISSUE TITLE
CTFd Import

### ISSUE THREAD

**Issue by profzeller** [cliffe/SecGen#129]
The current generated zip is incompatible with the new CTFd 2.0 that was released. I was going to work on this but wanted to see if this work was already being done.

**Comment by thomashaw** [comment]
No it isn't so please go ahead. We are currently using an as yet unreleased front end that interfaces with our oVirt VDI.

**Comment by profzeller** [comment]
Awesome. I sent Cliffe an email,  I will be working on code to interface with VMware in coming weeks. This will allow for adoption on NETLAB+, a big lab solution in US and worldwide.

http://www.netdevgroup.com

**Comment by Rajatkira** [comment]
I am able to generate the zip file using the command " **ruby secgen.rb --scenario scenarios/security_audit/team_project.xml build-project**" ,however, while trying to import the zip file to CTFd platform, I am getting an error message "**ValueError('No JSON object could be decoded',)**". Please  provide the inputs.

**Comment by profzeller** [comment]
Rajatkira,

I have not had a chance to commit the update for CTFd 2.0 and newer. For now I have been using the information in the zip to manually input into CTFd.

**Comment by Th3Prim3** [comment]
@thomashaw I finally got a chance to fork and create a pull request. Sorry I had it buried in another branch.
