### ISSUE TITLE
ESXI support

### ISSUE THREAD

**Issue by redwiz666** [cliffe/SecGen#130]
Thanks for the great tool. Have you though about adding VMware ESXI support? I found that vagrant has an esxi plugin what would accomplish this. I tried adding it and modifying the vagrant file to support the options but the virtualbox.box files that are downloaded will not work with it. I'm new to using vagrant so it might be user error. 

When using the esxi plugin i get the error 'the box you attempted to add doesn't match the provider specified' this is because the boxes downloaded are virtual box files.

I don't know enough ruby to work on writing a converter before attempting to add it.

I installed the plugin by 'vagrant plugin install vagrant-vmware-esxi'

Below is a link to the plugin and the documentation. 
https://github.com/josenk/vagrant-vmware-esxi 

Hopefully this support can be added

**Comment by redwiz666** [comment]
I forked your code and added ESXi support. Once I get the rest of the base boxed updated to ESXi I will do a pull request. I currently have 3 of the boxes complete.

**Comment by cliffe** [comment]
Great to hear. I look forward to the pull request. I believe @profzeller is working on something similar.

It would be helpful to have an automated approach to converting the base boxes, so they don't become out-of-sync across virtualisation platforms (I guess we could look at whether this could be automated building with Packer, or just some script to convert from the VirtualBox images to the others). We currently maintain our oVirt images and the public VirtualBox images manually -- there are some required differences, such as the VM guest agent software.

**Comment by Th3Prim3** [comment]
@redwiz666 I am finally at a point where I can work on this. I would love to see what you have. No sense in redoing effort. I never committed any changes during testing. I had a few key things I needed.

**Comment by cliffe** [comment]
I look forward to seeing some code. 

A good approach will be to add SecGen parameters that mirror the approach that was taken with oVirt, and ideally ensure any oVirt and VMware specific behaviour is moved out of secgen.rb and into the relevant helpers (lib/helpers/ovirt.rb and lib/helpers/vmware.rb) -- wherever possible with feature parity (and similar or shared parameters, for things such as setting usernames and passwords to the VDI infrastructure).

**Comment by redwiz666** [comment]
I'm actually done with adding in the functionally. I have it building most of the scenarios but there are 2 giving me issues, buts the same issues I get running on the main code base. I plan on doing a pull request soon to push it over but if you want to take a look and and see if I missed anything before I push it's in my repos (sorry I'm on my phone and cant link at the moment)
