### ISSUE TITLE
issues building basic_narrative scenario

### ISSUE THREAD

**Issue by redwiz666** [cliffe/SecGen#132]
I'm having issues building both the basic_narrative and team_project scenarios. Both of them are producing similar Nil errors. Below is the one from basic_narrative. When looking through 

> Module added: Account Generator (modules/generators/structured_content/account)
 Filtered to modules matching: {"type"=>["person"]} ~= (n=1)
 Selecting module: Person Profile Generator (modules/generators/structured_content/person)
 Receiving datastores: {"account"=>[{"variablename"=>"accounts", "access"=>"1", "access_json"=>""}]}
Error: can't add no data. Feeding [nil] into account
Check the scenario, not enough data is generated for this datastore (accounts) to access this index (1)
Failed to resolve scenario.
No conflicts, but failed to resolve scenario -- this is a sign there is something wrong in the config (scenario / modules)
Please review the scenario -- something is wrong.

team_project error below

> Module added: Debian 7 Wheezy Server (modules/bases/debian_puppet_32)
 Filtered to modules matching: {"module_path"=>[".*security_audit_remit"]} ~= (n=1)
 Selecting module: Security Audit Remit Generator (modules/generators/messages/security_audit_remit)
 Receiving datastores: {"business_name"=>[{"variablename"=>"organisation", "access"=>"all", "access_json"=>"['business_name']"}]}
 No element specified, e.g. access="0", for access_json="['business_name']": using (0)
Traceback (most recent call last):
	14: from secgen.rb:495:in `<main>'
	13: from secgen.rb:80:in `build_config'
	12: from secgen.rb:80:in `map!'
	11: from secgen.rb:81:in `block in build_config'
	10: from /home/redwiz666/SecGen/lib/objects/system.rb:50:in `resolve_module_selection'
	 9: from /home/redwiz666/SecGen/lib/objects/system.rb:50:in `each'
	 8: from /home/redwiz666/SecGen/lib/objects/system.rb:51:in `block in resolve_module_selection'
	 7: from /home/redwiz666/SecGen/lib/objects/system.rb:206:in `select_modules'
	 6: from /home/redwiz666/SecGen/lib/objects/system.rb:206:in `each'
	 5: from /home/redwiz666/SecGen/lib/objects/system.rb:207:in `block in select_modules'
	 4: from /home/redwiz666/SecGen/lib/objects/system.rb:207:in `each'
	 3: from /home/redwiz666/SecGen/lib/objects/system.rb:261:in `block (2 levels) in select_modules'
	 2: from /var/lib/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
	 1: from /var/lib/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:156:in `new'
/var/lib/gems/2.5.0/gems/json-2.2.0/lib/json/common.rb:156:in `initialize': no implicit conversion of nil into String (TypeError)
> 

I'm have looked through the xml file but i'm not seeing anything that is causing it.

**Comment by thomashaw** [comment]
Hi @redwiz666,

I've been unable to reproduce this. Which branch are you on? Have you made any changes to the scenario files?

**Comment by redwiz666** [comment]
I cloned the main branch with no modifications. I'll try deleting and re cloning to see if it work.

**Comment by redwiz666** [comment]
Reloading the files fixed the issue.

**Comment by thomashaw** [comment]
Great.
