### ISSUE TITLE
Issue building team_project scenario

### ISSUE THREAD

**Issue by redwiz666** [cliffe/SecGen#141]
When building the team_project scenario I am getting the following error.

> ==> web: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install apache2-mpm-prefork' returned 100: Reading package lists...
==> web: Building dependency tree...
==> web: Reading state information...
==> web: The following extra packages will be installed:
==> web:   apache2-utils apache2.2-bin apache2.2-common libapr1 libaprutil1
==> web:   libaprutil1-dbd-sqlite3 libaprutil1-ldap ssl-cert
==> web: Suggested packages:
==> web:   apache2-doc apache2-suexec apache2-suexec-custom openssl-blacklist
==> web: The following NEW packages will be installed:
==> web:   apache2-mpm-prefork apache2-utils apache2.2-bin apache2.2-common libapr1
==> web:   libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap ssl-cert
==> web: 0 upgraded, 9 newly installed, 0 to remove and 96 not upgraded.
==> web: Need to get 1508 kB of archives.
==> web: After this operation, 5032 kB of additional disk space will be used.
==> web: WARNING: The following packages cannot be authenticated!
==> web:   ssl-cert
==> web: E: There are problems and -y was used without --force-yes
==> web: Notice: /Stage[main]/Apache::Mod::Cgi/Apache::Mod[cgi]/File[cgi.load]: Dependency Package[httpd] has failures: true
==> web: Notice: /Stage[main]/Apache::Mod::Cgi/Apache::Mod[cgi]/File[cgi.load]: Dependency Package[apache2-mpm-prefork] has failures: true
==> web: Error: /Stage[main]/Apache::Mod::Prefork/Apache::Mpm[prefork]/Package[apache2-mpm-prefork]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install apache2-mpm-prefork' returned 100: Reading package lists...
==> web: Building dependency tree...
==> web: Reading state information...
==> web: The following extra packages will be installed:
==> web:   apache2-utils apache2.2-bin apache2.2-common libapr1 libaprutil1
==> web:   libaprutil1-dbd-sqlite3 libaprutil1-ldap ssl-cert
==> web: Suggested packages:
==> web:   apache2-doc apache2-suexec apache2-suexec-custom openssl-blacklist
==> web: The following NEW packages will be installed:
==> web:   apache2-mpm-prefork apache2-utils apache2.2-bin apache2.2-common libapr1
==> web:   libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap ssl-cert
==> web: 0 upgraded, 9 newly installed, 0 to remove and 96 not upgraded.
==> web: Need to get 1508 kB of archives.
==> web: After this operation, 5032 kB of additional disk space will be used.
==> web: WARNING: The following packages cannot be authenticated!
==> web:   ssl-cert
==> web: E: There are problems and -y was used without --force-yes

I tried looking through the puppet file for apache to add the --force-yes but I can't seem to find it.

**Comment by cliffe** [comment]
This is related to #140. The stretch base boxes should be working now. I've not had a chance to have a look at the VirtualBox wheezy box.
