### ISSUE TITLE
Seems like Vagrant can't establish SSH connection

### ISSUE THREAD

**Issue by sgjerken** [cliffe/SecGen#143]
Trying to use SecGen project to create vulnerable machines. I am using Ubuntu 18.4 dekstop (in virtualbox). I have followed the installation instructions, solved dependencies etc. When running "ruby secgen.rb run", the just stops when trying to authenticate. Adapter one is set to NAT. 
![Skjermbilde](https://user-images.githubusercontent.com/46353584/56129582-cc54af80-5f82-11e9-9127-d1a0be09d180.PNG)
SecGen machine displays following error:
![virtualiztion error](https://user-images.githubusercontent.com/46353584/56129604-daa2cb80-5f82-11e9-9cd6-b372408f7b97.PNG)

**Comment by cliffe** [comment]
You can enable VT-x virtualisation by editing your BIOS settings on boot.
