### ISSUE TITLE
vagrant default provider

### ISSUE THREAD

**Issue by feverGeek** [cliffe/SecGen#148]
I had installed virtualbox.But , when using the command "ruby secgen.rb run" I got the following error:
 No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
Non-zero exit status...
Error provisioning VMs, destroying VMs and exiting SecGen.
Loading vagrant (destroy -f) in /home/liuxer/tool/SecGen/projects/SecGen20190519_215637
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
Non-zero exit status...

**Comment by timiuaaa** [comment]
I am also running into the the same issue. Tried by explicitly launching the virtualbox but no success.
![image](https://user-images.githubusercontent.com/50011156/59424168-17196900-8e06-11e9-9251-3762635419c4.png)

**Comment by kblai518** [comment]
To get passed this I had to manually install the newest version of vagrant as the version in the tut does not support anything past VBox 5.1. However, I am now at another error where it says : 
Executable for vagrant not found: can't find gem vagrant (>= 0) with executable vagrant
Error provisioning VMs, destroying VMs and exiting SecGen.
