### ISSUE TITLE
Executable for vagrant not found: can't find gem vagrant

### ISSUE THREAD

**Issue by kblai518** [cliffe/SecGen#149]
Hi I am very new to all this and learning as I go, but I came across an issue that I am unsure how to fix. After running the secgen.rb file, I encounter this error: 
Executable for vagrant not found: can't find gem vagrant (>= 0) with executable vagrant
Error provisioning VMs, destroying VMs and exiting SecGen.
![secgen error](https://user-images.githubusercontent.com/52298801/60465247-81534b80-9c05-11e9-9f10-debc5793bbb6.JPG)

**Comment by jeremytourville** [comment]
Did you install both vagrant and gems?

```
wget https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.deb
sudo apt install ./vagrant_1.9.8_x86_64.deb

cd /home/user/bin/SecGen
bundle install
```
