### ISSUE TITLE
vsftpd backdoor isnt compatible with newer versions of the debian basebox

### ISSUE THREAD

**Issue by Aviio** [cliffe/SecGen#15]
The vsftpd backdoor module is very fragile and will only work with a specific version of the debian basebox.

Suggested fix: Either add a 'basebox' attribute to the metadata and ensure that if the vulnerability is selected, the corresponding basebox will be selected

Suggested fix: Re-write vsftpd module to be less fragile

**Comment by cliffe** [comment]
I believe this is resolved
