### ISSUE TITLE
failed to read scenario configuration file - windows

### ISSUE THREAD

**Issue by russweir** [cliffe/SecGen#152]
i tried to generate a windows scenario but failed to read the config file
<img width="441" alt="Screen Shot 2019-07-10 at 5 48 11 pm" src="https://user-images.githubusercontent.com/1886325/60960053-e14f9d80-a33b-11e9-917f-ea7a80eee7fa.png">

**Comment by thomashaw** [comment]
Hi @russweir,

You need to drop the leading `/` from `/scenarios/examples/windows_scenario.xml` as you're looking for the file in the `/scenarios/...` directory off the root directory, not the subdirectory `/home/username/SecGen/scenarios/...`
