### ISSUE TITLE
Gem Errors in secgen.rb

### ISSUE THREAD

**Issue by adrianwinckles** [cliffe/SecGen#154]
Was reinstalling SecGen to a new er build but when it came to running ruby secgen.rb run, I now get the following errors

_**aw@Secgen:~/SecGen$ ruby secgen.rb run
Traceback (most recent call last):
        8: from secgen.rb:9:in `<main>'
        7: from secgen.rb:9:in `require_relative'
        6: from /home/adrianwinckles/SecGen/lib/helpers/ovirt.rb:4:in `<top (required)>'
        5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        2: from /var/lib/gems/2.5.0/gems/ovirt-engine-sdk-4.3.0/lib/ovirtsdk4.rb:25:in `<top (required)>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require': /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /var/lib/gems/2.5.0/gems/ovirt-engine-sdk-4.3.0/lib/ovirtsdk4c.so) - /var/lib/gems/2.5.0/gems/ovirt-engine-sdk-4.3.0/lib/ovirtsdk4c.so (LoadError)
aw@Secgen:~/SecGen$**_

Any ideas?

**Comment by cliffe** [comment]
Looks like you might need to install the oVirt gem, even if you're not using oVirt.
