### ISSUE TITLE
Module failed to run (bundle exec ruby modules/generators/messages/random_ascii_art/secgen_local/local.rb)

### ISSUE THREAD

**Issue by divyanshub1** [cliffe/SecGen#155]
when i am running ruby secgen.rb run 
received 
Vagrant failed to initialize at a very early stage:

The home directory you specified is not accessible. The home
directory that Vagrant uses must be both readable and writable.

**Comment by jeremytourville** [comment]
You need to make sure permissions are set correctly

```
chmod -R 775 /home/user
chown -R user:user /home/user
```
