### ISSUE TITLE
vagrantcloud-files-production.s3.amazonaws.com

### ISSUE THREAD

**Issue by divyanshub1** [cliffe/SecGen#156]
**An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Failed writing body (0 != 16360)
Non-zero exit status...
Error provisioning VMs, destroying VMs and exiting SecGen.**
getting the error after running ruby secgen.rb run

**Comment by jeremytourville** [comment]
Which hypervisor is this for?  What scenario are you trying to run?  Please list your command line syntax when trying to run the scenario.
