### ISSUE TITLE
Default Password Not Working

### ISSUE THREAD

**Issue by Brambopulos** [cliffe/SecGen#159]
When following the README to create a SecGen VM, **ruby secgen.rb run** creates a machine that prompts for a debian-9 login and password without fail; however, any combination of root/puppet (the userpass suggested) fails to get me into the machine.

Why is this? Is there any information you might be able to provide?

![image](https://user-images.githubusercontent.com/56911161/67368126-9c86f580-f52b-11e9-80bc-ac3a2237da3a.png)

**Comment by jeremytourville** [comment]
Have you tried to login with UN/PW vagrant/vagrant?  That should let you get into the VM.
