### ISSUE TITLE
Use non-zero exit status for post provision tests failure?

### ISSUE THREAD

**Issue by dezull** [cliffe/SecGen#170]
VMs are deleted after failed tests, but Secgen still exits with zero status. Is this intended?

**Comment by thomashaw** [comment]
Hi @dezull,

No it isn't intended. Happy to accept a PR if. Alternatively, I am happy to fix this myself if you send me the output log (of a set of VMs that has failed post-provision tests, deleted the VMs, then exited with a zero status). 

Cheers,
Tom

**Comment by dezull** [comment]
@thomashaw Thanks. I will make a PR.
