### ISSUE TITLE
There was an error while executing `VBoxManage`, a CLI used by Vagrant

### ISSUE THREAD

**Issue by srajith** [cliffe/SecGen#174]
![error](https://user-images.githubusercontent.com/40263349/77251451-6bdeef80-6c74-11ea-96ae-cba96cb23627.png)
![versions](https://user-images.githubusercontent.com/40263349/77251489-9f217e80-6c74-11ea-91d2-6a36f0e7101b.png)

**Comment by hypercoyote** [comment]
If you solved this, it would be nice to share the solution.
