### ISSUE TITLE
SecGen with Openstack

### ISSUE THREAD

**Issue by nishant2019** [cliffe/SecGen#175]
How can we integrate SecGen with Openstack instead  of virtualbox

**Comment by cliffe** [comment]
Just a quick message to say that this involves integration into SecGen, similar to the Proxmox, oVirt, ESXI support. Also base modules need copying, and Vagrant plugin for the provider tested. 

Closing this issue as I'm cleaning up the SecGen issue tracker. Thanks for your interest in the project. 

You might be interested in our hosted solution: https://hacktivity.leedsbeckett.ac.uk/

**Comment by cliffe** [comment]
> As a note for anyone looking, Ill be working on a plugin for this for Openstack here at the RIT GCI Cyber Range Openstack Cluster, Ill submit a PR when I get it done, feel free to poke me if this post gets too old :)

Great! Good luck!
