### ISSUE TITLE
Error Install Packages While Build Project VMs

### ISSUE THREAD

**Issue by cccyber** [cliffe/SecGen#176]
Hope someone can help me with this.
While I build some projects (some success some failed), the VMs did not get created with the below error. Sometime same type of error with different packages. Can someone please point me to the direction how to fix this issue. (I run SecGen on Ubuntu1804)

**==> desktop: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install nmap' returned 100: E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
==> desktop: E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
==> desktop: Error: /Stage[main]/Nmap::Install/Package[nmap]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install nmap' returned 100: E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
==> desktop: E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?**

**Comment by thompslu** [comment]
Hi @cccyber can you please provide the full output of the VM set you’re trying to build. Please also include the scenario you’re trying to run. 

Also if vagrant destroys the VM , you step in to the directory So to speak to bring the VM back up for example 

cd /home/user/bin/SecGen/projects/project number-please change this to scenario generated number/

Once successfully in this folder do the following command :- vagrant up Once the VM has been brought up confirm this in virtual box. Do another command :- vagrant ssh 

From here once your logged in to vm manually install nmap. Let me know how this goes.

**Comment by cccyber** [comment]
Hi @thompslu Thanks for reply.
The scenario was container_escape. This is the latest SecGen package I downloaded yesterday.
I follow your suggestion manually build VMs and able to install nmap. 
Now, do I need to re-provision the VMs again? Since the VM got destroyed in the middle of automation process, and maybe other packages weren't installed or provisioned correctly.

attached text file is full out put of the scenario, error at the end.
[container_escape error.txt](https://github.com/cliffe/SecGen/files/4732534/container_escape.error.txt)

**Comment by thompslu** [comment]
Thankyou for the output @cccyber ,yes try the vagrant -provision command to manually reprovision the VM.  If you still get errors please let me know if I can be of any further assistance.

If your willing to take the extra step with the SecGen read through the "README-Creating-Scenarios" you will find how to make your own.  You can also make new bases with new versions of kali for example.

**Comment by cccyber** [comment]
Thanks @thompslu. Here is what works for me. (project: container_escape, 2VMs : desktop and esc_server)
1. manually build VMs by cd to the project folder and run _**vagrant up**_.
2. verify that VM created, then run _**vagrant ssh**_  and manually install nmap.
3. repeat 1 and 2 to build esc_server.
4. return to project folder run _**vagrant provision**_ to reprovision and install the rest of missing packages.

I stumble upon this SecGen project like I found gold, great learning environment.
will try to go through README-Creating-Scenario to eventually try to build my own project.
Thanks everyone who put this project together, cheer!
