### ISSUE TITLE
Basic build error  - 

### ISSUE THREAD

**Issue by adrianwinckles** [cliffe/SecGen#178]
Hi

I'd thought I'd successfully rebuilt Secgen in an Ubuntu 16.04 LTS platform by adapting to run virtualbox 5.1...

Tried the basic ruby secgen.rb run

but get the errors 

![image](https://user-images.githubusercontent.com/9204455/87689061-ab7b9b00-c77f-11ea-8768-ed66d0ada002.png)

Basically asking for Rubyencoder, isn't that a commercial product (14 days free trial)

Is there another fix for this?

Thanks

Adrian

**Comment by thompslu** [comment]
@adrianwinckles It’s not a SecGen issue as the projects are successfully creating, according to your screenshot It seems like it could be vagrant causing the issue. @cliffe i don’t know if you agree based on the result. Maybe try to reinstall vagrant. What version are you using ?

**Comment by adrianwinckles** [comment]
Yep, looks like a vagrant issue, rolled back from 1.9.8 to 1.9.7 and fixes those issues.

However now have a certificate isssue for vagrant  downloads for modulebases 

SSL certificate problem: certificate is not yet valid

Presume this is updating the bundle of certs in Vagrant

**Comment by thompslu** [comment]
I use vagrant 2.2.6 try this version let me know how you get on. There is a couple of issues with the vagrant version specified in the installation steps. You may get a few deprecation warnings about the type of adapter virtual box uses but it’s not a problem and works for me.

**Comment by Vector206** [comment]
![Screenshot_2020-09-17-14-22-20-921_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/69286452/93464256-90e5af80-f8f1-11ea-8e43-2460384ebcff.jpg)
Help

**Comment by thompslu** [comment]
An you be more specific what commands you are running, have you set up SecGen correctly I.e installing vagrant and the bundle Install before trying to run anything.
