### ISSUE TITLE
Ovirt Default Scenario

### ISSUE THREAD

**Issue by Xsenonn** [cliffe/SecGen#179]
Hi, I'm having problem with deploying default scenario on my Ovirt instance. Below is an error ruby (or rather Vagrant) produces.

==> escalation: Successfully added box 'ovirt4' (v0) for 'ovirt4'!
Bringing machine 'escalation' up with 'ovirt4' provider...
==> escalation: Creating VM with the following settings...
==> escalation:  -- Name:          SecGen-default-scenario-escalation
==> escalation:  -- Cluster:       Default
==> escalation:  -- Template:      debian_stretch_server_291118
==> escalation:  -- Console Type:  spice
==> escalation:  -- BIOS Serial:   
==> escalation:  -- Optimized For: 
==> escalation:  -- Description:   
==> escalation:  -- Comment:       
==> escalation:  -- Memory:        
==> escalation:  ---- Memory:      3000 MB
==> escalation:  ---- Maximum:     3000 MB
==> escalation:  ---- Guaranteed:  512 MB
==> escalation:  -- Cpu:           
==> escalation:  ---- Cores:       1
==> escalation:  ---- Sockets:     1
==> escalation:  ---- Threads:     1
==> escalation:  -- Cloud-Init:    false
Entity: line 1: parser error : Space required after the Public Identifier
\<\!DOCTYPE HTML PUBLIC \"\-\/\/IETF\/\/DTD HTML 2.0//EN">
                                                 \^
Entity\: line 1\: parser error \: SystemLiteral \" or \' expected
\<\!DOCTYPE HTML PUBLIC "\-\/\/IETF\/\/DTD HTML 2\.0\/\/EN\"\>
                                                \^
Entity: line 1: parser error : SYSTEM or PUBLIC, the URI is missing
\<\!DOCTYPE HTML PUBLIC \"\-\/\/IETF\/\/DTD HTML 2\.0\/\/EN\"\>
                                                 \^
==> escalation: An error occured. Recovering..
==> escalation: VM is not created. Please run \`vagrant up\` first.
/root/.vagrant.d/gems/2.4.9/gems/ovirt-engine-sdk-4.0.12/lib/ovirtsdk4/reader.rb:257:in \`initialize': Can't read first node (OvirtSDK4::Error)
	from /root/.vagrant.d/gems/2.4.9/gems/ovirt-engine-sdk-4.0.12/lib/ovirtsdk4/reader.rb:257:in \`new'
	from /root/.vagrant.d/gems/2.4.9/gems/ovirt-engine-sdk-4.0.12/lib/ovirtsdk4/reader.rb:257:in \`read'
	from /root/.vagrant.d/gems/2.4.9/gems/ovirt-engine-sdk-4.0.12/lib/ovirtsdk4/service.rb:66:in \`check_fault'
	from /root/.vagrant.d/gems/2.4.9/gems/ovirt-engine-sdk-4.0.12/lib/ovirtsdk4/services.rb:35570:in \`add'
	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-ovirt4-1.2.3/lib/vagrant-ovirt4/action/create_vm.rb:79:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-ovirt4-1.2.3/lib/vagrant-ovirt4/action/set_name_of_domain.rb:17:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:121:in \`block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in \`block in run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in \`busy'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in \`run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/call.rb:53:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /root/.vagrant.d/gems/2.4.9/gems/vagrant-ovirt4-1.2.3/lib/vagrant-ovirt4/action/connect_ovirt.rb:32:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/config_validate.rb:25:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/handle_box.rb:56:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in \`block in run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in \`busy'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in \`run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:238:in \`action_raw'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:209:in \`block in action'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:613:in \`lock'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in \`call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in \`action'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/batch_action.rb:86:in \`block (2 levels) in run'
Non-zero exit status...
Not going to destroy escalation, since it does not exist
Failed. Not retrying. Please refer to the error above.

What may be wrong with the log above

**Comment by Xsenonn** [comment]
Okay, so it seems that I have solved problem by changing API url to <IP/Hostname>/ovirt-engine/api. Now I'm dealing with error below.
`Fault reason is "Operation Failed". Fault detail is "Entity not found: GetVmTemplate". HTTP response code is 404.`
As I've said I have fresh install of Ovirt Instance, and aside from Blank template I don't have any other (assuming that Vagrant is looking for some kind of template). Maybe here someone had bumped on such error?

**Comment by thompslu** [comment]
Have you setup some templates up for each OS for instance for example kali Linux base vm template, Debian stretch base and so on. This needs to be the case for each OS as mentioned in order for it to work with the oVirt infrastructure of which SecGen runs upon. It’s easier to definitely have a host and and your own domain if this permits but if only for lab testing then IP’s should work but it does get confusing. Without looking in detail I believe that vagrant made need a few tweaks. @cliffe would be the best person to give you a response on this part. Let me know how you get on.

**Comment by Xsenonn** [comment]
Thanks for the hint. I'll try that out. I'll contact cliffe if I get stuck

**Comment by thompslu** [comment]
Cool, I’ve set mine up myself but obviously each system works and is tailored to different needs dependent on infrastructure etc again depending on how much detail you can disclose about systems also.

I’m more than happy to explain my setup but I’d rather if @cliffe give you the advice first and if I have his permission to share my setup config in the first instance then I will. I have extensive documentation that I have made but again I’m going to make it more generic so that hopefully I can put a link somewhere that shows how to get SecGen up and running.
