### ISSUE TITLE
Non - zero exit status

### ISSUE THREAD

**Issue by Vector206** [cliffe/SecGen#181]
![Screenshot_2020-09-17-15-26-16-673_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/69286452/93470177-284f0080-f8fa-11ea-9555-2b23def5dac0.jpg)

**Comment by thompslu** [comment]
Please provide more information in relation to the problem. Thankyou for providing the error however it would be more helpful to know exactly what command you are trying to run and if you have setup up SecGen correctly.

**Comment by Vector206** [comment]
Здравствуйте, настраивал по текстовику который идёт вместе с secgen.
Использовал команду ruby secgen.rb run

**Comment by Vector206** [comment]
> обновил vagrant до 2.2.10 
![Screenshot_2020-09-17-14-22-20-921_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/69286452/93510513-f9e91980-f929-11ea-8032-c50c80da7690.jpg)
Команда ruby secgen.rb run

**Comment by Vector206** [comment]
![Screenshot_2020-09-17-21-10-28-129_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/69286452/93510691-4d5b6780-f92a-11ea-8f90-ef935ecae66f.jpg)
ruby secgen.rb run
Версия vagrant 2.2.10

**Comment by thompslu** [comment]
я сделал сообщение на странице нерешенных проблем. вам нужно будет запустить виртуальную машину вручную. Я посмотрю, что у меня есть за веб-ссылку, и опубликую ее в этом обширном разделе справки. С уважением, thompslu.

**Comment by Vector206** [comment]
Запустил, не помогает

**Comment by Vector206** [comment]
С версией vagrant 1.9.8 
![Screenshot_2020-09-17-22-20-54-748_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/69286452/93517445-24d86b00-f934-11ea-96cc-53e5b018293a.jpg)

**Comment by thompslu** [comment]
Привет, извините, с предоставленной ограниченной информацией я не могу помочь с ошибками, которые вы получаете. Есть ли у вас опыт программирования или разработки.

Translation EN_GB

Hi sorry, with the limited information provided i cant help the error(s) that you recieve.Do you have any programming or development experience.

**Comment by Vector206** [comment]
А у вас есть, готовая виртуалке с secgen, которая функционирует?

**Comment by thompslu** [comment]
Привет, извините за задержку, виртуальная машина не предоставляется. На самом деле ожидается, что у вас уже есть виртуальная машина для разработки или физическая машина для разработки, так как существует множество вариантов, которые подходят для лабораторной или сетевой настройки.

Translation EN_GB
Hi sorry for the delay, no VM is provided. It is really expected that you already have a development VM or physical machine to develop on as they're many options available to how it fits with a lab or existing network setup.

**Comment by Vector206** [comment]
Не могу заставить работать этот проект

**Comment by thompslu** [comment]
Проект работает отлично, если вы боретесь с ним, пожалуйста, посмотрите онлайн-ресурсы для таких вещей, как основные команды Linux. Какую версию ubuntu и vagrant вы используете? Я бы посоветовал начать с использования 16.04 LTS и vagrant 2.2.6. Я скоро свяжу здесь некоторые из моих предыдущих комментариев с другими сообщениями. Не стесняйтесь просматривать открытые вопросы, и вы увидите некоторые из моих других сообщений, которые могут быть полезны для ответа на ваш вопрос.

Translation EN_GB
The project works absolutley great, if you are struggling with it please take a look at online resources for things such as basic linux commands. Which version of ubuntu and vagrant do you use? I would suggest to start with using 16.04 LTS and vagrant 2.2.6. I will link some of my previous comments in other posts on here soon. Please feel free to look at the open issues and you will see some of my other posts that may be useful to answering your question.

**Comment by Vector206** [comment]
Мне пока не удается настроить требует  Rubyencoder

**Comment by Vector206** [comment]
![Screenshot_2020-10-03-20-02-57-430_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/69286452/94997425-a0345080-05b3-11eb-8108-2512cd8322fd.jpg)
