### ISSUE TITLE
Работа без интернета

### ISSUE THREAD

**Issue by Vector206** [cliffe/SecGen#183]
День добрый, хочу притащить в офис, а там нет интернета. Как закачать все модули и собирать конкретно из них

**Comment by thompslu** [comment]
Привет, обычно вам нужно быть подключенным к Интернету, чтобы загрузить свои сценарии и виртуальные машины в свою систему. Вам нужно будет просмотреть документ сценария и основные команды на домашней странице SecGen, например, что-то вроде этого, чтобы вы начали

ruby secgen.rb - сценарии сценариев / ctf / flawed_fortress_1.xml запустить

Обратите внимание, что вы уже должны быть в каталоге SecGen, чтобы выполнить вышеуказанное. Пожалуйста, дайте мне знать, если я могу помочь.

Искренне Ваш

Thompslu

Translation EN_GB

Hi usually you need to be connected to the internet to download your scenarios and VM's to your system. You will need to look at the scenario document and basic commands on the SecGen home page, for example something like this to get you going

ruby secgen.rb --scenario scenarios / ctf / flawed_fortress_1.xml run

Note that you must have already been in the SecGen directory to accomplish the above. Please let me know if I can help.

Yours faithfully

Thompslu
