### ISSUE TITLE
Развитие SecGen

### ISSUE THREAD

**Issue by Vector206** [cliffe/SecGen#186]
Это очень хороший проект, респект авторам. Я пытаюсь решить проблему развертывания машин, без интернета. У меня есть много проектов, которые я создал с подключением к интернету. После выполнения команды vagrant up в директории проекта начинается процесс. Появляются все новые ошибки. Идея создания локального интернета даст дополнительный импульс развития SecGen. Если авторов заинтересовало данное предложение от помощи не отказался, сам пока не справляюсь

**Comment by GolTech42** [comment]
Напишите мне! Срочно!

**Comment by thompslu** [comment]
Привет, в чем проблема, GolTech42, извините Vector206 за поздний ответ! с точки зрения проекта - это действительно то, как далеко вы продвинетесь в своих собственных развертываниях. Вы можете обнаружить, что ошибки происходят, это не сам SecGen, а его основы. Вы можете создавать свои собственные базы для проекта, но это зависит от вас, в каких базах Linux вы решите создать, это файл readme, как создавать базы для виртуального бокса с помощью vagrant.


EN_GB Translation


Hi whats the problem GolTech42, sorry Vector206 for the late response! in terms of the project its really how far you take it in your own deployments. You may find that errors proceed this is not SecGen itself its rather the bases. You can make your own bases for the project but thats up to you in what linux bases you decide to create, their is a readme file how to make bases for virtualbox using vagrant.

Kind Regards

Luke Thompson
________________________________

**Comment by GolTech42** [comment]
help me do secgen offline broth!
