### ISSUE TITLE
Problem running secgen.rb

### ISSUE THREAD

**Issue by razer382** [cliffe/SecGen#189]
I've been able to either find all other issues ive been having online or by finding out however I can't seem to find anything on this error message. This is the error message it gives when I try to run secgen.

> Module failed to run (bundle exec ruby modules/generators/messages/welcome_message/secgen_local/local.rb) Failed to resolve scenario. During scenario generation 1 module conflict(s) occured .... Tried re randomising -.. Please review the scenario -- something is wrong.

**Comment by jeremytourville** [comment]
Have you confirmed that the the gems were installed properly and don't have dependency issues.  I am running Ubuntu 20.04 and noted several issues when trying to get the environment setup initially.  The directions as written don't seem to work anymore.  At least not without a little modification.
