### ISSUE TITLE
Timed out while waiting for the machine to boot.

### ISSUE THREAD

**Issue by Cookedbeefchops** [cliffe/SecGen#193]
Context:
- I'm using Virtualbox to run Ubuntu 16.04.7 LTS. 
- I'm using a 'Bridged Adapter' instead of default NAT mode in my host virtualbox. 
- Managed to build SecGen in Ubuntu 16.04.7 LTS without any errors. However I notice when I ran    _ruby secgen.rb --scenario scenarios/ctf/flawed_fortress_1.xml run_ it kept producing this warning on each VM:

![image](https://user-images.githubusercontent.com/25220748/121232424-2c75e080-c8c4-11eb-9c67-9c37b9f73b73.png)

It also seems to re-create new vagrant keys as it deemed insecure. Not sure if this has anything to do with the error. 

After it produced 3 VMs it produced this error:

![image](https://user-images.githubusercontent.com/25220748/121232783-88d90000-c8c4-11eb-9777-08921abccb4a.png)

Seems like a connection error, not sure why. Another thing I noticed was that there was a warning regarding Virtualbox Guest Additions not matching the installed version.

**Comment by cliffe** [comment]
The issue isn't related to the yellow Puppet deprecation warnings, or the vagrant key being replaced, both are normal. It's just a networking issue with your VMs. Try using vagrant without SecGen, to troubleshoot.

**Comment by thompslu** [comment]
Unfortunately due to it been a project that has so much potential the bases haven’t been updated for some time. Exact software versioning and other modifications that have taken place may give you a few errors. Many packages also have been updated extensively to match certain Linux versions at certain points in time. Feel free to take the project the way you want explore , try make sense of what the code is doing and try to modify based on that strategy. Good luck in your journey with this project.

Kind Regards

Luke Thompson
________________________________

**Comment by Cookedbeefchops** [comment]
> Hi @Cookedbeefchops unfortunately due to it been a project that has so much potential the bases haven’t been updated for some time. Exact software versioning and other modifications such as use on different hypervisors are just a few to mention that have taken place and as such probably why you're experiencing a few errors/issues. Many packages also have been updated extensively to match certain Linux versions at certain points in time. Feel free to take the project the way you want explore , try make sense of what the code is doing and try to modify based on that strategy. Good luck in your journey with this project. The only thing I would recommend Is trying to cd /projects/SecGen20210609_034915 then use the vagrant up command and ssh in to the machine to push updates or If you want to try your own bases and what requirements are expected visit this link https://github.com/cliffe/SecGen/blob/master/README-Creating-Bases.md also visit the vagrant link on how to package base boxes https://www.vagrantup.com/docs/boxes/base not sure if this helps you. @cliffe not sure If you agree to close ticket as I experienced this too when I first started with the project. It's more a user issue around base updates not SecGen itself, possibly some minor changes to /etc/apt/sources.list.d/ with apt-get dist-upgrade from user from a user perspective . Kind Regards thompslu

Thanks a lot for the prompt replies! I believe my initial titled issue "Timed out while waiting for the machine to boot" has been solved so I will close this issue. Thanks for the suggestions as well, I will look into updating the sources.list.

**Comment by cliffe** [comment]
Yeah, sorry, we haven't updated the Virtualbox bases in a while. There was a discussion in another issue, but try starting the bases in .vagrant/bases and install updates. Good luck!
