### ISSUE TITLE
Kali web metapackage fails to build: unable to locate the 'kali-tools-web' dependency

### ISSUE THREAD

**Issue by tvergilio** [cliffe/SecGen#199]
The repository may have moved or needs to be mapped in. At the moment, the Commando or Team Project scenarios, for example, are failing to build.

**Comment by cliffe** [comment]
You need to make sure the Kali base is up-to-date, as the names of the meta-packages changed. If you start the base box up directly, and apply updates, it should sort that out.

**Comment by cliffe** [comment]
We need to update the public Virtualbox base boxes, but in the meantime you can update your local copy manually.

**Comment by tvergilio** [comment]
Thanks, I'll do that. Would you mind posting the path of where it is located here, please?

**Comment by cliffe** [comment]
/home/USER/.vagrant.d/boxes/
