### ISSUE TITLE
Commando: login sometimes fails even when using correct credentials

### ISSUE THREAD

**Issue by tvergilio** [cliffe/SecGen#202]
This happens intermittently. Most VMs commissioned will work just fine, but occasionally there is one where the default credentials will not work. Need to investigate why this is happening and fix.

![VirtualBox_Kali_default_1629301739891_3076_22_08_2021_11_45_34](https://user-images.githubusercontent.com/6339599/130352395-4fbf8db1-1643-4c0a-9c1f-2af92ef18d69.png)

![VirtualBox_Kali_default_1629301739891_3076_22_08_2021_11_43_37](https://user-images.githubusercontent.com/6339599/130352400-9f82bdeb-d967-4cda-a39d-55a731636e15.png)

![Screenshot from 2021-08-22 11-53-00](https://user-images.githubusercontent.com/6339599/130352526-d3771629-bb9f-4727-893e-3c232fee23e6.png)

**Comment by tvergilio** [comment]
The application seems to be querying the wrong table. It is querying a table called 'Users' when the table is actually called 'users1'.
![VirtualBox_Kali_default_1629301739891_3076_22_08_2021_12_01_19](https://user-images.githubusercontent.com/6339599/130352716-753ddbb7-ed31-41b5-a6f2-3dbdc0d9b0da.png)

**Comment by tvergilio** [comment]
This looks bad... why is the 1 on line 21 hardcoded into the table name?

![Screenshot from 2021-08-22 12-25-22](https://user-images.githubusercontent.com/6339599/130353345-c52d64f6-5fa8-467a-98d4-59d113da706e.png)

**Comment by tvergilio** [comment]
Why create two identical tables with identical contents?

![Screenshot from 2021-08-22 12-36-20](https://user-images.githubusercontent.com/6339599/130353662-5febdac6-a75f-49dd-baf0-f9100c91a326.png)

**Comment by cliffe** [comment]
I agree. Suggest you remove the trailing 1 copy.

**Comment by tvergilio** [comment]
One definite problem I found is that 'user' is a reserved name in mySQL, so we need to remove it from the users_table_names list. Every time 'user' or 'User' randomly comes up, there are problems.

**Comment by tvergilio** [comment]
There is more to it than meets the eye... the password ends up being different in both tables, even though the code that inserts the record is the same 🤷🏻‍♀️ 

It is 'password1' here...

![VirtualBox_Kali_default_1629301739891_3076_22_08_2021_17_55_34](https://user-images.githubusercontent.com/6339599/130363690-2b68059f-355e-4645-ade0-cab58936c704.png)

and 'password123' here!
![VirtualBox_Kali_default_1629301739891_3076_22_08_2021_17_55_58](https://user-images.githubusercontent.com/6339599/130363694-106120ce-e9c7-4c3e-b4a1-a3b67ec797ab.png)

Even though the source code shows that the same value is inserted in both tables: @admin_password

![Screenshot from 2021-08-22 17-59-54](https://user-images.githubusercontent.com/6339599/130363689-8a217582-11bf-4c3f-be17-c4c404c3acb9.png)

![Screenshot from 2021-08-22 17-59-34](https://user-images.githubusercontent.com/6339599/130363683-ba7395f0-9f71-4c07-94d8-692dc4acd0aa.png)

**Comment by tvergilio** [comment]
I am leaving the "duplicate" table there until I understand better why it was created and what effect it has on everything else.

**Comment by cliffe** [comment]
That means that different parameter values are being passed into the module(s). Likely an issue with the scenario or module defaults being used. The scenario needs to randomise the value there, and pass the same value into the different modules.

**Comment by cliffe** [comment]
I.e. there is a module (or multiple modules) that have a parameter named "user_table_name". A value can be passed in from the scenario itself (and the scenario can randomise it for example), or if none is specified (nothing is passed to a parameter), it will take a default value (defined in the secgen_metadata.xml file for that scenario) -- which again, by default it might be randomised.

**Comment by cliffe** [comment]
This explains how parameterisation of modules works, and how modules can be chained together:
https://github.com/cliffe/SecGen/blob/master/README-Creating-Scenarios.md#advanced-scenarios-parameterisation

This is how commando is intended to work, there are separate modules used to generate php code, content, etc.

Also, this explains (towards the end) how modules can have default values:
https://github.com/cliffe/SecGen/blob/master/README-Modules-Metadata.md

**Comment by tvergilio** [comment]
Thanks, Cliffe. I am not sure I get what the code is doing in `store.sql.erb` though. 

Ultimately, it generates a SQL script with a number of statements. If the  `<%= @user_table_name %>` parameter did not always evaluate to the same value within the script, the `ALTER TABLE`  and  `INSERT` statements would not work. 

The screenshots below are all within the same file. If the dynamically-generated values were to vary, the script would not make sense. Am I missing something? 🤔 

![Screenshot from 2021-08-23 14-05-16](https://user-images.githubusercontent.com/6339599/130452652-e7f42b2c-f77a-45e7-aa1a-43594c30acaf.png)
![Screenshot from 2021-08-23 14-10-28](https://user-images.githubusercontent.com/6339599/130453101-ef833dd2-61b3-44df-9bdc-b10e845f5d4c.png)

**Comment by cliffe** [comment]
I've not tried to look at the code for Commando carefully, but I'd guess maybe the scenario isn't saving the value in a datastore, and reusing the same value, so it's being generated twice (accidentally?)
