### ISSUE TITLE
Issues finding the Kali Repo when building CTF Scenario

### ISSUE THREAD

**Issue by Bloxy487** [cliffe/SecGen#215]
Hi all,

Now this could be similar to https://github.com/cliffe/SecGen/issues/199, but unsure, so I am asking here. I apologies if duplicate, and fully appreciate any support offered.

When running the scenario builder I am receiving a lot of repo errors. AS seen in the attached image.

I am running a fresh version of Ubuntu Desktop on a bare metal machine, not a virtual machine. uname -a results:
`Linux ubuntu-phys 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

I am assuming this is not as simple as just adding the Kali repos to my Ubuntu machine, but more so modifying a base box somewhere? Perhaps? 

I appreciate any support.

Cheers,
Bloxy

![image](https://user-images.githubusercontent.com/25493871/150699136-6c5eb4d4-24ad-4269-b37f-c5e2287769f6.png)

**Comment by cliffe** [comment]
Please see the tips in the README about updating base boxes.

Closing this issue as I'm cleaning up the SecGen issue tracker. Thanks for your interest in the project. 

You might be interested in our hosted solution: https://hacktivity.leedsbeckett.ac.uk/
