### ISSUE TITLE
The following SSH command responded with a non-zero exit status.

### ISSUE THREAD

**Issue by exCrowned** [cliffe/SecGen#216]
When I run the **ruby secgen.rb run** command, I run into the following error:

mkdir -p /tmp/vagrant-puppet; chmod 0777 /tmp/vagrant-puppet

**Stdout from the command:**

**Stderr from the command:**

**Non-zero exit status...**
**Error provisioning VMs, destroying VMs and exiting SecGen**

It either gives me the error above, or hangs indefinitely when I try to run **ruby secgen.rb run** and I never get the **VM's created** line in the command line.

![unknown](https://user-images.githubusercontent.com/54496140/153777435-8cc72642-ddf8-4564-b04a-27db333669e2.png)

**Comment by Tez01** [comment]
I have same error. Did you find  a solution to this?

**Comment by Tez01** [comment]
Update: I found a fix for me. It seems the box 'modules_bases_debian_puppet_32'  seems to be outdated. I manually downloaded the file by following instructions here: https://github.com/cliffe/SecGen/issues/114. And than it ran.
