### ISSUE TITLE
Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)

### ISSUE THREAD

**Issue by jminnick** [cliffe/SecGen#224]
Can this not be installed on an AWS Ubuntu instance?

![Screen Shot 2022-08-31 at 3 32 22 PM](https://user-images.githubusercontent.com/3810135/187766518-97031e13-9c56-4989-8a2c-129a1ef38d19.png)

have tried passing --cpu-cores 1 .. and even hardcoding in the Vagrantfile. no dice.

**Comment by havardMoe** [comment]
Unsure if this is relevant, but I got this error when I tried to initialize a VirtualBox-image with network-mode: bridge, with adapter bridge0. It went away when I changed network mode.
