### ISSUE TITLE
Builder conflicting requirements

### ISSUE THREAD

**Issue by jaaayc** [cliffe/SecGen#226]
im on macos using chruby ruby 3.1.2 

when i try bundle update i get the following error: 

Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby

    digest-sha3 was resolved to 1.1.0, which depends on
      Ruby (~> 2.2)

**Comment by SasquatchSecurity** [comment]
When I came across this, I had to bump down to a 2.x release of Ruby. 3.x did not work.

**Comment by cliffe** [comment]
I believe we currently run Ruby 2.7.0

**Comment by havardMoe** [comment]
Awesome. That resolved the issue!
However, I now get a new error "An error occurred while installing digest-whirlpool (1.0.3), and Bundler cannot
continue.".

I can create a new issue on this

**Comment by cliffe** [comment]
> Awesome. That resolved the issue! However, I now get a new error "An error occurred while installing digest-whirlpool (1.0.3), and Bundler cannot continue.".
> 
> I can create a new issue on this

This might help:
https://github.com/cliffe/SecGen/issues/221#issuecomment-1159300326
