### ISSUE TITLE
Bundler unable to install digest-whirpool [Windows, Ruby 2.7.6, Bundler 2.1.4]

### ISSUE THREAD

**Issue by havardMoe** [cliffe/SecGen#227]
When running "bundler update" trying to install from the Gemfile I get the following error:
`
An error occurred while installing digest-whirlpool (1.0.3), and Bundler cannot continue.
`
```
When opening the logging file it says:
   26 C:/Ruby27-x64/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an exe    cutable file. (RuntimeError)
   27 You have to install development tools first.
   28         from C:/Ruby27-x64/lib/ruby/2.7.0/mkmf.rb:613:in `try_cpp'
   29         from C:/Ruby27-x64/lib/ruby/2.7.0/mkmf.rb:1124:in `block in have_header'
   30         from C:/Ruby27-x64/lib/ruby/2.7.0/mkmf.rb:971:in `block in checking_for'
   31         from C:/Ruby27-x64/lib/ruby/2.7.0/mkmf.rb:361:in `block (2 levels) in postpone'
   32         from C:/Ruby27-x64/lib/ruby/2.7.0/mkmf.rb:331:in `open'
   33         from C:/Ruby27-x64/lib/ruby/2.7.0/mkmf.rb:361:in `block in postpone'
   34         from C:/Ruby27-x64/lib/ruby/2.7.0/mkmf.rb:331:in `open'
   35         from C:/Ruby27-x64/lib/ruby/2.7.0/mkmf.rb:357:in `postpone'
   36         from C:/Ruby27-x64/lib/ruby/2.7.0/mkmf.rb:970:in `checking_for'
   37         from C:/Ruby27-x64/lib/ruby/2.7.0/mkmf.rb:1123:in `have_header'
   38         from extconf.rb:6:in `<main>'
```

However, my ruby-installation is supposed to be "with devkit". So I am unsure which development tools it means.
Does anyone know the answer to this?

**Comment by cliffe** [comment]
Honestly I wouldn't attempt to install on a Windows system. Good luck!

**Comment by havardMoe** [comment]
> Honestly I wouldn't attempt to install on a Windows system. Good luck!

I would ideally do it on an ubuntu machine on virtual-box, but I had some errors initializing more virtual machines within a virtual machine

I will try a little more, update you here if I find a solution, if not, i will install ubuntu on a laptop and try from there.

**Comment by Halfwhit** [comment]
I recommend using a VM, and ensuring nested virtualization is enabled/supported. Then use rbenv to set the local ruby version to 2.7, and I think I then used "rbenv exec bundler install"
