### ISSUE TITLE
gitlist_040--1-/home/git/repositories/secret_files/-append

### ISSUE THREAD

**Issue by carenamae** [cliffe/SecGen#231]
@cliffe Hi everyone, I need help. I am new to SecGen and I tried to run a scenario but I got an error like this. Please help. Thanks!
![Screenshot at Jan 23 10-39-40](https://user-images.githubusercontent.com/90629542/214082259-d7d73222-f02d-4e43-ba6f-a4a6aa16d32a.png)

**Comment by cliffe** [comment]
Closing this issue as I'm cleaning up the SecGen issue tracker. Thanks for your interest in the project. 

You might be interested in our hosted solution: https://hacktivity.leedsbeckett.ac.uk/
