### ISSUE TITLE
virtualbox issues using ubuntu 2004 on wsl2

### ISSUE THREAD

**Issue by ltham79** [cliffe/SecGen#288]
I am having the hardest time getting SecGen set up!!! It took me a few days to get this far. I have installed SecGen finally. When I run the secgen.rb 

gets all the way to the end and errors

------------------------------------------------------------------------------------------
Project files created.
Building project: /home/syn/SecGen/projects/SecGen20230717_091121
Loading vagrant (up) in /home/syn/SecGen/projects/SecGen20230717_091121
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
Non-zero exit status...
Error provisioning VMs, destroying VMs and exiting SecGen.
Loading vagrant (destroy -f) in /home/syn/SecGen/projects/SecGen20230717_091121
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
Non-zero exit status...
-------------------------------------------------------------------------------

I have tried everything to reinstall virtual box and vagrant files and Im just stuck!!!!!!!
I hope you guys can help I am really excited to use SecGen as my pen testing playground.

Thanks in advance

-Syn

**Comment by cliffe** [comment]
Hi there. Sorry, this isn't going to be super useful, but you haven't got vagrant (and/or VirtualBox) installed properly. Good luck.

**Comment by ltham79** [comment]
can you use secgen with vmware?

**Comment by cliffe** [comment]
No, not currently.

**Comment by ltham79** [comment]
well thanx for your help anyway :-(

**Comment by cliffe** [comment]
Install Linux dual boot, or you can even run SecGen in a Linux VM, if you enable nested virtualisation (if your BIOS supports it)

**Comment by ltham79** [comment]
Im working on that now. Still reading some other posts on getting vbox with wsl2 seems the problem is hyper V. I use wsl because its so much faster than vm and dont have the ram needed for a upperclass linux vm lol

**Comment by ltham79** [comment]
https://askalice97.medium.com/running-virtualbox-inside-of-wsl2-with-nested-virtualization-bde85046fe8d has figured it out but I dont uunderstand half of the information on the page
