### ISSUE TITLE
projects/Project#/mount directory removal

### ISSUE THREAD

**Issue by thomashaw** [cliffe/SecGen#29]
During the project creation phase an empty directory, named 'mount', is being created within the projects/ProjectX/ directory.

![selection_006](https://cloud.githubusercontent.com/assets/3964474/15864741/3089d4fa-2cd0-11e6-94e3-a2bb9a6c485e.png)

This can be removed.

**Comment by cliffe** [comment]
With my overhaul I have done away with the mount dirs all together. Aiming to merge my changes in the next day or so (just some minor cleaning up to do).
