### ISSUE TITLE
Im having trouble with VBoxManage

### ISSUE THREAD

**Issue by KarlKnopf** [cliffe/SecGen#290]
I have gotten the error below and need help understanding it:

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "vboxnet1", "--ip", "172.28.128.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

If you need more information I would be happy to attempt to provide more.

**Comment by cliffe** [comment]
Sorry, I've not used VirtualBox in a while, but I think you need to set up a local NIC. Good luck!

**Comment by BDragisic** [comment]
Apologies, but I am also getting this same error and I'm not sure what you mean. I've now tried running SecGen on 2 different Ubuntu hosts (1 virtualised and 1 bare metal server) and this same error has appeared on both instances. 

Can you provide any more elaboration on how to fix?
