### ISSUE TITLE
Vagrant unable to provision VM: apt-get update --fix-missing error

### ISSUE THREAD

**Issue by stanley0010** [cliffe/SecGen#292]
I am just running the default scenario with `ruby secgen.rb run`. However, apt-get in VM failed.

<img width="817" alt="image" src="https://github.com/cliffe/SecGen/assets/25721992/c3edab72-74df-482d-b53a-f95e1304626b">

I think the problem is that the base box is using Debian 9. And when you try to do `apt-get update` on it, the following errors are shown: 
<img width="1296" alt="image" src="https://github.com/cliffe/SecGen/assets/25721992/847e93a7-84ef-40b4-b47c-b41bd1227ab3">

@cliffe Can you please advise what we can do? Thank you

**Comment by infosecirvin** [comment]
SecGen is making a VM from Debian Stretch, a OS that is no longer supported by Debian in the current repository list. You'll need to use Debian 10 and up.

**Comment by ST-AR-X** [comment]
> SecGen is making a VM from Debian Stretch, a OS that is no longer supported by Debian in the current repository list. You'll need to use Debian 10 and up.

Can you provide instructions/guide on how to make SecGen running on newest Debian version? Thanks.

**Comment by infosecirvin** [comment]
Before running a scenario, ensure in the xml file that Debian 10 or newer is selected. There are some Debian 9 vms in the xml, so you’ll need to check before executing.Alternatively, if you set up a local repository server for Debian 9 that would respond via DNS as deb.debian.org, Debian.net and security.debian.org, you could run secgen normally and create Debian 9 images.   On Wed, Sep 27, 2023 at 4:10 AM, ST-AR-X ***@***.***> wrote:  

SecGen is making a VM from Debian Stretch, a OS that is no longer supported by Debian in the current repository list. You'll need to use Debian 10 and up.

Can you provide instructions/guide on how to make SecGen running on newest Debian version? Thanks.
