### ISSUE TITLE
Vagrant Deployment issues - proxmox

### ISSUE THREAD

**Issue by harryalderton** [cliffe/SecGen#295]
Hi 

We are trying to deploy SecGen to Proxmox. We've fixed multiple issues including the 
- dummy.box no longer working as its unable to download. 
- The instructions for Proxmox doesn't specify the user needs to be 'user@pam' for example. 
- Then the below error whenever I run 

```
ruby secgen.rb --proxmoxuser root@pam --proxmoxpass xxxx --proxmox-url https://xxxx:8006/api2/json --proxmox-node xxx --proxmox-network xxxx --proxmox-vlan 6 run
```

```
==> escalation: Mounting shared folders...
    escalation: /vagrant => /home/x/SecGen/projects/SecGen20231124_155702
==> escalation: Running provisioner: puppet...
==> escalation: Running Puppet with environment production...
==> escalation: Error: Could not parse application options: invalid option: --environmentpath
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Non-zero exit status...
Error provisioning VMs, destroying VMs and exiting SecGen.
```

How do I fix this?

**Comment by harryalderton** [comment]
To update this the debug log

`DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: stderr: Error: Could not parse application options: invalid option: --environmentpath
 INFO interface: info: Error: Could not parse application options: invalid option: --environmentpath
 INFO interface: info: ==> escalation: Error: Could not parse application options: invalid option: --environmentpath
==> escalation: Error: Could not parse application options: invalid option: --environmentpath
DEBUG ssh: stderr: 

DEBUG ssh: Exit status: 1
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

**Comment by cliffe** [comment]
Hi. I've not seen that error, but keep in mind you have to use this version:
https://github.com/cliffe/vagrant-proxmox/

We don't currently publish proxmox bases so you will need to create a buster vm, boardly following these instructions
https://github.com/cliffe/SecGen/blob/master/README-Creating-Bases.md

Good luck!

Keep in mind that we have just started providing commercial access to our Hacktivity platform, so feel free to reach out if you are interested in a hosted solution. https://hacktivity.leedsbeckett.ac.uk/
