### ISSUE TITLE
VBoxManage Error

### ISSUE THREAD

**Issue by OrangeYellowMan** [cliffe/SecGen#301]
![help](https://github.com/cliffe/SecGen/assets/126493792/9ec91544-6ce4-4e8e-a7d5-8fb097f1376f)

Anyone know how to fix this issue?

**Comment by ryanwessels** [comment]
In newer versions of Virtualbox you need to make sure you allow the networks in /etc/vbox/networks.conf (you may need to create it).

Syntax for your example would be:

* 172.28.128.0/24

If you wanted to allow any network (not recommended):

* 0.0.0.0/0
