### ISSUE TITLE
Video Walkthrough 

### ISSUE THREAD

**Issue by JosephTaylor125** [cliffe/SecGen#304]
I have been struggling to get this downloaded on all versions such as Ubuntu 20, Ubuntu 16.04, and Kali Linux

Is it possible to provide a video walkthrough to see if the problems I encounter a problem for other people?

**Comment by cliffe** [comment]
Hi @JosephTaylor125. Thanks for your interest in the project. 

I agree it can be a bit of a faf to get SecGen installed. Good luck! Using Ubuntu is what I'd suggest, but I haven't installed from scratch in a while.

Closing this issue as I'm cleaning up the SecGen issue tracker. 

You might be interested in our hosted solution: https://hacktivity.leedsbeckett.ac.uk/
