### ISSUE TITLE
SSH Command Responded with a Non-Zero Status

### ISSUE THREAD

**Issue by OrangeYellowMan** [cliffe/SecGen#305]
![image](https://github.com/cliffe/SecGen/assets/126493792/8b646f83-8926-439a-9917-e3eb24454735)

I'm not exactly too sure what the issue is here. I am running the "ruby secgen.rb run" command and getting this error.

Would anyone know how to solve this?

**Comment by Bloomers7577** [comment]
Duplicate of https://github.com/cliffe/SecGen/issues/292
