### ISSUE TITLE
General Help Questions

### ISSUE THREAD

**Issue by OrangeYellowMan** [cliffe/SecGen#310]
I have installed it on Ubuntu 20.04 and have fixed several of the installation problems I ran into, but I’m running into problems running some of the projects.

Firstly, it seems like on a default run, I’m always getting a Debian 9 OS. Is there a way I can change into a different base box, like CentOS or Windows? I would like to create vulnerable machines in those as that is what I will mostly be dealing with.

Secondly, I can not run any Windows versions in scenarios/examples. I have installed everything below “To use the Windows base box…” within the Github instructions and still can’t get it to work. Any reason for this? 

Third, when I get a scenario example with a GUI, I’m not able to login with any default password. How would I get in the vulnerable machine to perform blue team skills?

Additionally, I can seem to just do "ruby secgen.rb run". I have to build the project first, then cd into that project, then use vagrant up. Is there a reason for this?

**Comment by cliffe** [comment]
Hi -- Thanks for your interest in the project. For smoothest experience, create a Debian Buster base box (by updating the Stretch one).

The default password will be saved in a file in the project directory, or try vagrant:puppet

Closing this issue as I'm cleaning up the SecGen issue tracker. 

You might be interested in our hosted solution: https://hacktivity.leedsbeckett.ac.uk/
