### ISSUE TITLE
Empty <conflict> <software_name></conflict> </software_name> causes conflicts.

### ISSUE THREAD

**Issue by thomashaw** [cliffe/SecGen#48]
When searching for two services, if one of the services has an empty conflict tag secgen is unable to find a matching module.

Example:
![image](https://cloud.githubusercontent.com/assets/3964474/16952494/48a9c196-4dc1-11e6-8f6c-f9bf637ba05c.png)

Works when commenting out the conflict element + sub element:

![image](https://cloud.githubusercontent.com/assets/3964474/16952527/7307c8de-4dc1-11e6-98f1-e702e62bcd14.png)

**Comment by cliffe** [comment]
Don't do that then. :neutral_face: 

Are there examples of this in the current modules?

**Comment by cliffe** [comment]
I guess it wouldn't hurt catch this fringe case
