### ISSUE TITLE
Regex conflict issue?

### ISSUE THREAD

**Issue by Jjk422** [cliffe/SecGen#51]
Issue where the conflict tag will causes other services to be marked as invalid due to placement of conflict inside service.
E.g. the php module may have the conflict tag of php, therefore no other php services are selected, however a service like phpmyadmin (that may require the php module) is being marked as invalid due to the conflict (as far as I can tell).
For the PHP module this can be avoided with the conflict php5 or php-language instead of just php, however this may not be possible with all other services and may cause more complex code in the future.

This may be a regex issue, however I am not sure on the exact cause, whether this is intentional or whether this is a issue we need to worry about.

**Comment by cliffe** [comment]
As we discussed, lets only define module conflicts when we need to, but the solution to what you describe is to use the regexp '^php$' rather than 'php' as this will require a complete match.
