### ISSUE TITLE
SecGen not creating machine in virtualbox

### ISSUE THREAD

**Issue by Jjk422** [cliffe/SecGen#59]
After upgrading my laptop to Ubuntu 16.04 (Xenial) from Ubuntu 14.04 (Trusty) and installing the new version of virtualbox (5.1), SecGen seems to be generating machines but not passing them to virtualbox.
I am wondering if anyone else has had any issues like this or whether they know what the problem is.
I have a feeling that it is due to using the new virtualbox versions, however I cannot seem to install virtualbox 4.3 on ubuntu 16.04.

**Comment by thomashaw** [comment]
I've got a feeling that I've had the same issue when using the latest version of VirtualBox + vagrant. Couldn't tell you which caused the issue as I downgraded both but  have you tried manually downloading the 4.3 .deb and installing it from [here](http://download.virtualbox.org/virtualbox/4.3.38/)?

**Comment by Jjk422** [comment]
Ye, tried downloading the old 4.3 version, doesn't support Ubuntu 16.04 (Xenial), only up to Ubuntu 14.04 (Trusty). 
Really we need to get SecGen working with new Virtualbox versions, however I do not know whether the bottlenecking in upgrading is due to puppet, vagrant or SecGen itself. 
Anyway, if Virtualbox 4.3 is needed I'll most likely have to downgrade back to 14.04 (unless anyone else has a solution). 
We do need to find out why it doesn't seem to be supporting new Virtualbox versions, as 4.3 is only getting security fixes and important fixes with official support ending on 2015/12.

**Comment by egg82** [comment]
The vagrant version used has some compatibility issues with VB 5x. It even spits out an error about that when used. Not sure if there's been an update to fix that or not yet, but it's safe to assume you'll need 4.3 for it to work properly.

**Comment by Jjk422** [comment]
After upgrading all the software (vagrant, ruby gems, VirtualBox, puppet) again, SecGen seems to be working perfectly on VirtualBox 5.1. So unless anyone else is having this problem, I will close the issue.
