### ISSUE TITLE
Vulnerable WebApps - Question

### ISSUE THREAD

**Issue by kerberosmansour** [cliffe/SecGen#96]
@cliffe @lewisardern Does SecGen support the autogeneration of webapps?
I could see a lot of infrastructure issues, but I'm more interested in web vulnerabilities i.e. injection attacks ala SQLi/XXE/Commandi etc..

I would like to have a random vulnerable webapp generator as part of a project I would like to work on.

Also do you support docker?

**Comment by cliffe** [comment]
Hi. Thanks for contacting us. This is something we are working on, but there is room for alternative approaches in separate SecGen modules. Hopefully we will have a first version to share sometime in a week or so, and will build on that to develop a new web security module. If you are happy to wait a few weeks you could see how we are approaching it, and add more security vulnerabilities to the site?

**Comment by LewisArdern** [comment]
@kerberosmansour I have some ideas for the web side of things, if you are at OWASP this month we can catch-up as the new code should be shipped by the students currently working on that aspect.

**Comment by kerberosmansour** [comment]
Ok great!
Thanks

**Comment by kerberosmansour** [comment]
See you at the next OWASP London event

**Comment by cliffe** [comment]
SecGen has a bunch of vulnerable webapps, including some that have randomised vulnerabilities. 

Closing this issue as I'm cleaning up the SecGen issue tracker. Thanks for your interest in the project. 

You might be interested in our hosted solution: https://hacktivity.leedsbeckett.ac.uk/
