### ISSUE TITLE
Question? How do you make it public?

### ISSUE THREAD

**Issue by GotchaPython** [cliffe/SecGen#97]
How do you make it host public? I changed the scenario to public_network but it seems not to work. Thanks.

**Comment by GotchaPython** [comment]
anyone?

**Comment by cliffe** [comment]
Hi,

Try this:
`ruby secgen.rb -s scenarios/examples/public_network.xml r`

Obviously, the keep in mind using public networks you are likely to expose a vulnerable VM to the network.

Hope that helps.

Cheers,
Cliffe.

**Comment by GotchaPython** [comment]
I was able to run that command, but it does not look like it makes it public. When nmaping the ip address I see no open ports etc. Any other ideas?

**Comment by cliffe** [comment]
Login to the VM root: puppet and check ifconfig, and netstat

**Comment by 8bitkiwi** [comment]
Sorry for a stupid question - but what are the creds to use when you say "Login to the VM root"

I can't seem to find what I should use, but it could be right under my nose :(

**Comment by thomashaw** [comment]
The default root password is 'puppet'.

**Comment by eelsivart** [comment]
Does the "public_network" support the "range" attribute? I just tried creating a basic scenario with the "public_network" and wanted to set a static ip for it with "range", but when I run it, I get an error "Failed to resolve scenario". The scenario works fine when I take out the "range". Thanks!

**Comment by cliffe** [comment]
The scenario.xml works by filtering to select a network specified in modules/networks. There is only the one network that I added in the above commit, using dhcp. If you want a network range you can create a new network module. Have a look in modules/networks, and add a public_network_2, and let us know how you get on. Feel free to make a pull request when you have that working. We can create that for you if you get stuck.

**Comment by eelsivart** [comment]
Ahh, I see, got it. I was able to get it working by adding a new public_network_2 modules folder with an appropriate secgen_metadata.xml. And I had to change how I referenced the network in my scenario to: 
`<network module_path=".*public_network_2"/>`

Thanks!

**Comment by cliffe** [comment]
Glad it's sorted. Have fun with SecGen!

**Comment by srajith** [comment]
> Hi,
> 
> Try this:
> `ruby secgen.rb -s scenarios/examples/public_network.xml r`
> 
> It will prompt for the interface to bridge to. We should probably add support for providing that information via command arguments.
> 
> Obviously, keep in mind that using public networks you are likely to expose a vulnerable VM to the network.
> 
> Hope that helps.
> 
> Cheers,
> Cliffe.

how to set on host only adapter
